### ISSUE TITLE
BaseModel'w Call error

### ISSUE THREAD

**Issue by Ahmad-Sajjad** [ahadnawaz585/ReactronBase#2]
![IMG-20240827-WA0001](https://github.com/user-attachments/assets/4fbfd4b0-c87b-467e-a0f2-0ba7875a921e)
Unable to add baseModel's call in components

**Comment by ahadnawaz585** [comment]
I discovered that using Prisma in a browser environment isn’t feasible as it requires Node. 

## Plan 🛠️

1. **Remove Prisma**: It's incompatible with the browser.
2. **Use `better-sqlite3`**: Switch to this library for database management.

## Next Steps 📋

- **Testing**: Verify `better-sqlite3` functionality.
- **Schema Examples**: Provide examples for schema and modeling.
- **Integration**: Update Electron bundle accordingly.

Stay tuned for updates. This is in response to a GitHub issue.

**Comment by ahadnawaz585** [comment]
Hi @Ahmad-Sajjad  👋,

I’m excited to let you know that we’ve addressed the database issue you reported! 🎉

**Here’s what’s new:**

**1. Switched to `knex`** 🔄:
We’ve replaced `better-sqlite3` and `prisma` with `knex` for SQLite database management. This change ensures better compatibility and provides more flexibility in interacting with the database.

**2. Updated Database Path Configuration** 📂:
The database path is now set dynamically:
- **Development:** Uses a local path for easier access during development.
- **Production:** Stores the database in the user data directory, adhering to production practices.

**3. Added IPC Handler for Database Queries** 🛠️:
We’ve introduced a new IPC handler for executing raw SQL queries from the renderer process. This allows for seamless database operations.

**Here’s how you can use the updated setup:**

1. **Install Dependencies** 📦:
   Make sure `knex` and `sqlite3` are installed by running:
   ```bash
   npm install knex sqlite3
   ```

2. **Perform Database Operations** 💻:
   Use the IPC channel `query-database` to send raw SQL queries from the renderer process to the main process. For example:
   ```typescript
   // In the renderer process
   ipcRenderer.invoke('query-database', 'SELECT * FROM your_table')
     .then(result => console.log(result))
     .catch(error => console.error(error));
   ```

3. **Verify Functionality** ✅:
   Test the setup to ensure that your database interactions are working as expected.

If you have any more questions or run into issues, feel free to reach out! 😊


Happy Coding 🚀
