### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by Ahmad-Sajjad** [ahadnawaz585/ReactronBase#3]
It is nit rendering and showing this error
![IMG-20240825-WA0045](https://github.com/user-attachments/assets/532f3111-ac68-43a7-a457-88d0e12db450)

**Comment by ahadnawaz585** [comment]
This was due to webpack build but now in last version i have upgraded to vite build use that by taking pull `git pull` or use npx create-reactronbase <app-name> !!! Happy coding🚀🚀
